site_name: QHB ED Survival Guide
theme:
  name: material

nav:
  - How to Refer: how-to-refer.md
  - Numbers: numbers.md
  - Pathways & Special Cases: pathways.md
  - Trauma & Burns: trauma.md
  - Hospitals & Networks: hospitals.md
  - About: about.md
